# Application name and port
spring.config.import=optional:file:../.env[.properties]
spring.application.name=eureka-server
server.port=${EUREKA_PORT:8761}

# Prevents the server from registering with itself
eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false
